import { Injectable } from '@angular/core';
import { Question } from './questions/question.model';

@Injectable({
  providedIn: 'root',
})
export class QuestionService {
  questions: Question[] = [
    {
      // Round 1
      // Name a famous video game character
      id: 0,
      answer1: 'Mario',
      answer2: 'Link',
      answer3: 'Lara Croft',
      answer4: 'Sonic',
      answer5: 'Master Chief',
      answer6: 'Pikachu',
      answer7: '',
      answer8: '',
      points1: 38,
      points2: 20,
      points3: 13,
      points4: 12,
      points5: 9,
      points6: 8,
      points7: 0,
      points8: 0,
    },
    {
      // Name a computer mouse brand
      id: 1,
      answer1: 'Logitech',
      answer2: 'Razer',
      answer3: 'Dell',
      answer4: 'Roccat',
      answer5: 'HP',
      answer6: '',
      answer7: '',
      answer8: '',
      points1: 45,
      points2: 37,
      points3: 8,
      points4: 7,
      points5: 3,
      points6: 0,
      points7: 0,
      points8: 0,
    },
    {
      // Name a game that gets better with mods
      id: 2,
      answer1: 'Skyrim',
      answer2: 'Minecraft',
      answer3: 'Grand Theft Auto',
      answer4: 'Garys Mod',
      answer5: 'Fallout',
      answer6: '',
      answer7: '',
      answer8: '',
      points1: 38,
      points2: 27,
      points3: 15,
      points4: 12,
      points5: 8,
      points6: 0,
      points7: 0,
      points8: 0,
    },
    {
      // Round 2
      // Name a racing game
      id: 3,
      answer1: 'Forza',
      answer2: 'Mario Kart',
      answer3: 'Need For Speed',
      answer4: 'Trackmania',
      answer5: 'Gran Turismo',
      answer6: '',
      answer7: '',
      answer8: '',
      points1: 34,
      points2: 23,
      points3: 22,
      points4: 11,
      points5: 10,
      points6: 0,
      points7: 0,
      points8: 0,
    },
    {
      // Name a part of the human body
      id: 4,
      answer1: 'Arm',
      answer2: 'Genitalia',
      answer3: 'Head',
      answer4: 'Leg',
      answer5: 'Hand',
      answer6: 'Toe',
      answer7: 'Brain',
      answer8: '',
      points1: 28,
      points2: 18,
      points3: 16,
      points4: 14,
      points5: 9,
      points6: 8,
      points7: 7,
      points8: 0,
    },
    {
      // Name something gamers blame when they die
      id: 5,
      answer1: 'Lag',
      answer2: 'Team',
      answer3: 'Themselves',
      answer4: 'Hardware',
      answer5: 'Cheating',
      answer6: 'The Game',
      answer7: '',
      answer8: '',
      points1: 53,
      points2: 24,
      points3: 10,
      points4: 6,
      points5: 5,
      points6: 2,
      points7: 0,
      points8: 0,
    },
    {
      // Round 3
      // Name a zombie game
      id: 6,
      answer1: 'Left 4 Dead',
      answer2: 'Call of Duty: Zombies',
      answer3: 'Plants vs. Zombies',
      answer4: 'Resident Evil',
      answer5: 'The Walking Dead',
      answer6: 'Last of Us',
      answer7: '',
      answer8: '',
      points1: 31,
      points2: 26,
      points3: 19,
      points4: 11,
      points5: 7,
      points6: 6,
      points7: 0,
      points8: 0,
    },
    {
      // Name a Nintendo character
      id: 7,
      answer1: 'Mario',
      answer2: 'Luigi',
      answer3: 'Yoshi',
      answer4: 'Zelda',
      answer5: 'Bowser',
      answer6: 'Birdo',
      answer7: '',
      answer8: '',
      points1: 60,
      points2: 11,
      points3: 10,
      points4: 8,
      points5: 6,
      points6: 5,
      points7: 0,
      points8: 0,
    },
    {
      // Name a Twitch streamer
      id: 8,
      answer1: 'xQcOW',
      answer2: 'Hylifoxx',
      answer3: 'Ninja',
      answer4: 'Mizkif',
      answer5: 'Disguisted Toast',
      answer6: '',
      answer7: '',
      answer8: '',
      points1: 45,
      points2: 25,
      points3: 11,
      points4: 10,
      points5: 9,
      points6: 0,
      points7: 0,
      points8: 0,
    },
    {
      // Round 4
      // Name a thing you do before entering a boss room
      id: 9,
      answer1: 'Save game',
      answer2: 'Mentally prepare',
      answer3: 'Status check',
      answer4: 'Heal up',
      answer5: 'Reload',
      answer6: '',
      answer7: '',
      answer8: '',
      points1: 34,
      points2: 25,
      points3: 19,
      points4: 16,
      points5: 6,
      points6: 0,
      points7: 0,
      points8: 0,
    },
    {
      // Name a Pokémon type
      id: 10,
      answer1: 'Fire',
      answer2: 'Water',
      answer3: 'Electric',
      answer4: 'Dragon',
      answer5: 'Grass',
      answer6: 'Steel',
      answer7: '',
      answer8: '',
      points1: 42,
      points2: 23,
      points3: 16,
      points4: 10,
      points5: 6,
      points6: 3,
      points7: 0,
      points8: 0,
    },
    {
      // Name a mob in Minecraft
      id: 11,
      answer1: 'Creeper',
      answer2: 'Zombie',
      answer3: 'Skeleton',
      answer4: 'Enderman',
      answer5: 'Zombie Pigman',
      answer6: 'Sheep',
      answer7: 'Pig',
      answer8: 'Villager',
      points1: 33,
      points2: 20,
      points3: 12,
      points4: 11,
      points5: 8,
      points6: 7,
      points7: 5,
      points8: 4,
    },
    {
      // Round 5
      // Name a video game item that gives health, other than a potion
      id: 12,
      answer1: 'Food',
      answer2: 'Medkit',
      answer3: 'Hearts',
      answer4: '',
      answer5: '',
      answer6: '',
      answer7: '',
      answer8: '',
      points1: 57,
      points2: 30,
      points3: 13,
      points4: 0,
      points5: 0,
      points6: 0,
      points7: 0,
      points8: 0,
    },
    {
      // Name a letter of the alphabet
      id: 13,
      answer1: 'A',
      answer2: 'B',
      answer3: 'Z',
      answer4: 'F',
      answer5: 'P',
      answer6: 'K',
      answer7: 'E',
      answer8: '',
      points1: 39,
      points2: 16,
      points3: 15,
      points4: 12,
      points5: 9,
      points6: 5,
      points7: 4,
      points8: 0,
    },
    {
      // Name a video game to play with friends
      id: 14,
      answer1: 'Mario Kart',
      answer2: 'Golf With Your Friends',
      answer3: 'Mario Party',
      answer4: 'Minecraft',
      answer5: 'Among Us',
      answer6: 'League of Legends',
      answer7: '',
      answer8: '',
      points1: 36,
      points2: 18,
      points3: 15,
      points4: 14,
      points5: 9,
      points6: 8,
      points7: 0,
      points8: 0,
    },
    {
      // Round 6
      // Name a popular speedrun game
      id: 15,
      answer1: 'Super Mario 64',
      answer2: 'Minecraft',
      answer3: 'Pokémon',
      answer4: 'Soulsbourne',
      answer5: 'Sonic',
      answer6: '',
      answer7: '',
      answer8: '',
      points1: 42,
      points2: 34,
      points3: 10,
      points4: 8,
      points5: 6,
      points6: 0,
      points7: 0,
      points8: 0,
    },
    {
      // Name a video game object that gives loot when broken
      id: 16,
      answer1: 'Pottery',
      answer2: 'Chests',
      answer3: 'Crates',
      answer4: 'Barrels',
      answer5: 'Lucky/Coin Blocks',
      answer6: 'Enemies',
      answer7: '',
      answer8: '',
      points1: 38,
      points2: 29,
      points3: 12,
      points4: 10,
      points5: 7,
      points6: 4,
      points7: 0,
      points8: 0,
    },
    {
      // Name a video game currency
      id: 17,
      answer1: 'Gold',
      answer2: 'Rupees',
      answer3: 'Riot Points',
      answer4: 'V-bucks',
      answer5: 'Simoleons',
      answer6: 'Bells',
      answer7: '',
      answer8: '',
      points1: 32,
      points2: 28,
      points3: 16,
      points4: 9,
      points5: 8,
      points6: 7,
      points7: 0,
      points8: 0,
    },
    {
      // Round 7
      // Name a monkey or ape
      id: 18,
      answer1: 'Donkey Kong',
      answer2: 'Baboon',
      answer3: 'Harambe',
      answer4: 'Orangutan',
      answer5: 'Chimpansee',
      answer6: 'Diddy Kong',
      answer7: '',
      answer8: '',
      points1: 44,
      points2: 15,
      points3: 12,
      points4: 11,
      points5: 10,
      points6: 7,
      points7: 0,
      points8: 0,
    },
    {
      // Name a shooter video game
      id: 19,
      answer1: 'Valorant',
      answer2: 'Call of Duty',
      answer3: 'Counter Strike',
      answer4: 'Battlefield',
      answer5: 'Overwatch',
      answer6: 'Halo',
      answer7: 'Doom',
      answer8: 'Borderlands',
      points1: 29,
      points2: 23,
      points3: 13,
      points4: 12,
      points5: 10,
      points6: 6,
      points7: 4,
      points8: 3,
    },
    {
      // Name a something you find on a gamers desk
      id: 20,
      answer1: 'Keyboard',
      answer2: 'Mouse',
      answer3: 'Monitor',
      answer4: 'Beverage',
      answer5: 'Headset',
      answer6: 'PC',
      answer7: '',
      answer8: '',
      points1: 32,
      points2: 28,
      points3: 16,
      points4: 9,
      points5: 8,
      points6: 7,
      points7: 0,
      points8: 0,
    },
  ];

  getQuestions() {
    return this.questions;
  }

  getQuestionByid(id: number): Question {
    return this.questions.filter((question) => question.id === id)[0];
  }
}
